INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Lil Stevie', false, false, 35.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Black Thunder', false, false, 27.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Blanche', false, false, 44.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Knobby McGee', false, false, 57.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Blackthorn Original', false, false, 38.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('SheepGuard, Guardian of the Sheep', false, false, 41.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Uncle Pete', false, false, 51.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Krakanos', false, false, 34.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Astoria', false, false, 36.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Mirror Pond', false, false, 30.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('The Stony Cudgel', false, false, 48.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Harding', false, false, 42.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Stinson', false, false, 43.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Right Angle Arnie', false, false, 50.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Long Throw Larry', false, false, 29.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Timestopper', false, false, 39.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Martin Fury', false, false, 40.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Drifting Dorry', false, false, 46.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Sparkles', false, false, 30.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Swanson', false, false, 37.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Samsonite', false, false, 28.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Ronald', false, false, 33.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Samwise', false, false, 44.00);
INSERT INTO shillelaghs (name, ordered, shipped, price) VALUES ('Jeff', false, false, 42.00);

INSERT INTO customers (username, first_name, last_name, address, email, admin) VALUES ('morty', 'morton', 'higsby', '9999 Placeyplace Dr Kevinson, KY 24468', 'yorspur@yorspur.com', false);
INSERT INTO customers (username, first_name, last_name, address, email, admin) VALUES ('kilsport', 'kilsburton', 'portersmouth', '103 Yorkinson Pl Martinson, GA 34417', 'therspen@therspen.com', true);
INSERT INTO customers (username, first_name, last_name, address, email, admin) VALUES ('spurson', 'spurtersly', 'jeff', '51903 Phoinon Ct Jefferson, JF 27844', 'spurson@murson.com', false);

INSERT INTO methods (payment_type, card_type, customer_id, number, routing_number, confirmation_number, expiration_date) VALUES (0, 1, 3, 1677546223856798, null, 469, '2024-12-01');
INSERT INTO methods (payment_type, card_type, customer_id, number, routing_number, confirmation_number, expiration_date) VALUES (1, null, 3, 138549762554, 136985662247, null, null);